# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d08762d68744be7ae4d4c1e90703bcffb25f965cbc84d6e366f2fc4a05e05b9d651057d25133d9ed37083c7bac53b3a3e8f112f4e624682ea3fba55acd012720

test:
  secret_key_base: ca7795133636e191dfda4705521eefc4a73179cb5a64f5ce50d7f88f5f591dd5caf0e9d34258c47471bfd5802fd53bfa9137d0a6b4e6cf03b36f91e00548fd70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
